spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    #url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    #username: ${MYSQL_USER}
    #password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089
